theme: jekyll-theme-cayman
show_downloads: false
title: Ethereum Beacon Chain checkpoint sync endpoints
description: A community maintained list of public Beacon Chain checkpoint sync endpoints with health checks
