name: Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: "check"
  cancel-in-progress: true

jobs:
  check:
    name: check & update endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout remote
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'eth-clients/checkpoint-sync-endpoints'
          ref: main
          path: remote
      - name: Combine endpoints
        run: |
          export TARGET=endpoints.yaml
          # always want mainnet ordered first
          echo "mainnet:" > $TARGET
          cat remote/endpoints/mainnet.yaml >> $TARGET
          # dump all endpoints into target except for mainnet
          for body in remote/endpoints/*.yaml; do filename=$(basename -- ${body%.*});  if [ "$filename" != "mainnet" ]; then echo "" >> $TARGET; echo "${filename}:" >> $TARGET; cat "$body" >> $TARGET; echo "" >> $TARGET; fi; done
      - name: Setup node 18
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 18
      - name: Install node modules
        run: npm ci
      - name: Update endpoints data
        run: npm start
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: endpoints
          path: endpoints.yaml
      - name: Save endpoints (artifact)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: endpoints
          retention-days: 90
          path: _data/endpoints.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: "chore(ci): update endpoints"
          default_author: github_actions
